# Generated by Django 4.0.6 on 2022-07-26 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUserModel',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(verbose_name='생년월일')),
                ('age', models.IntegerField(verbose_name='나이')),
                ('introduction', models.TextField(verbose_name='소개')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.customusermodel', verbose_name='사용자')),
            ],
        ),
    ]
