# Generated by Django 4.0.6 on 2022-07-26 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caresheet', '0005_remove_caresheet_weight'),
        ('user', '0004_alter_customusermodel_main_species'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUserModel',
            new_name='User',
        ),
    ]
