# Generated by Django 4.0.6 on 2022-07-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caresheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caresheet',
            name='sex',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=20, verbose_name='성별'),
        ),
    ]
