# Generated by Django 4.0.6 on 2022-07-26 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caresheet', '0002_alter_caresheet_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(verbose_name='무게')),
                ('record_date', models.DateTimeField(auto_now_add=True, verbose_name='기록일')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='개체명', to='caresheet.caresheet')),
            ],
        ),
    ]
