# Generated by Django 4.0.6 on 2022-07-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caresheet', '0003_weightrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightrecord',
            name='record_date',
            field=models.DateField(auto_now_add=True, verbose_name='기록일'),
        ),
    ]
